Update webpack settings to create main.js and main.css files
cerner/terra-asset-bundle pull request #6
Opened 2023-04-05 14:32 UTC by nikhitasharma

Update webpack settings to create main.js and main.css files

2023-04-14 16:42 UTC, seanturk requested changes

2023-04-14 16:42 UTC, seanturk commented on package.json
> +    "mini-css-extract-plugin": "^1.3.1"
Please alphabetize

2023-04-14 16:42 UTC, seanturk commented on package.json
> +    "webpack-dev-server": "^4.11.1"
Alphabetize here as well

2023-04-14 19:35 UTC, lqdev00 reviewed
How large are the files? Did we consider chunking the files (perhaps by import)? I can imagine many applications not needing all of Terra at a time.

2023-04-14 19:35 UTC, lqdev00 commented on webpack.config.js
> +      chunkFilename: 'main.css',
How come we're calling the files `main` instead of something like `terra`?

2023-04-17 20:41 UTC, nikhitasharma commented
> How large are the files? Did we consider chunking the files (perhaps by import)? I can imagine many applications not needing all of Terra at a time.

The main.js file is 4 MB and main.css is 1.3 MB. It was discussed that we would create a single js chunk for everything for now and explore chunking later based on requirements.

2023-04-17 20:46 UTC, nikhitasharma commented on webpack.config.js
> +      chunkFilename: 'main.css',
We can name the files whatever we want by modifying the webpack.config.js file. The default from terra-toolkit webpack config is main.js and main.css 
@seanturk  Do we want to change this?

2023-04-18 15:55 UTC, seanturk approved these changes

2023-04-18 20:32 UTC, merged